"""add phone number

Revision ID: 09263f07b0e0
Revises: ad944368d4a9
Create Date: 2022-11-25 20:40:58.181282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09263f07b0e0'
down_revision = 'ad944368d4a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
